# Generated by Django 3.2.5 on 2022-01-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
            preserve_default=False,
        ),
    ]
